### ISSUE TITLE
--skip-pg will still copy DATABASE_URL

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-fork#17]
We had one customer who used `--skip-pg` flag and did manually create a forked database (since it's faster for lots of prod database), but since `heroku fork` command copied `DATABASE_URL` during the creation, creating a new database with forked app didn't have it promote as a primary database, so they were accidentally writing the things to the original application.

We should consider skipping copying `DATABASE_URL` when `--skip-pg` flag was passed to avoid the mess, or at lease we should super warn this :warning:

**Comment by keiko713** [comment]
Or, at least have a better doc: https://devcenter.heroku.com/articles/fork-app

**Comment by jdx** [comment]
https://github.com/heroku/heroku-fork/pull/18

**Comment by benbuckman** [comment]
This is contrary to my expectation: `--skip-pg` should not _create_ a new database, but if `DATABASE_URL` points to an _existing_ database, shouldn't it keep the config value?

Per https://devcenter.heroku.com/articles/fork-app (as noted above),

> If the `DATABASE_URL` value was manually set on `sourceapp`, for instance to share a database with another app or to add a parameter like `?pool=10`, its value will be copied to `targetapp` verbatim. In other words, `targetapp` will be configured to use the same database as `sourceapp`.

This change seems to contradict that documentation.

What is the correct way now to maintain `DATABASE_URL` on a forked app – set it manually with `heroku config` after the app is created?

**Comment by keiko713** [comment]
Sorry for the super late reply and thanks for reporting this. That Dev Center article is somewhat incorrect actually, first of all you can't modify `DATABASE_URL` config var manually anymore. Seems like that part was documented for years ago when we still didn't have that restriction and hasn't been updated. I'll work on to update the doc.

You could still share one database with multiple apps [by attaching](https://devcenter.heroku.com/articles/managing-add-ons#using-the-command-line-interface-attaching-an-add-on-to-another-app), but if you attach in this way, you really shouldn't just copy the config variable to the forking app. It'll loose the information of "attaching", and whenever we need to update the `DATABASE_URL` (e.g. there is an issue with underlying instance and have to move the database to the different host) as it won't be updated automatically.

If you would like to share the one database between the original app and forked app, you should be attaching the addon after the fork.
