### ISSUE TITLE
Revert deprecation (please?)

### ISSUE THREAD

**Issue by barbogast** [heroku/heroku-fork#28]
Hi,

I would very much appreciate if you could revert the decision to deprecate `heroku fork`. I use it quite often to create test and staging apps. It would be very tedious and error prone to have to do this manually.

Using review apps as an alternative doesn't work for us since we don't use github.

So... please?

**Comment by jdx** [comment]
You can continue to use it as a plugin you can install, so it will not go away, but we will not be maintaining it
