### ISSUE TITLE
Plugin won't install - npm error

### ISSUE THREAD

**Issue by AndrewDPalmer** [heroku/heroku-fork#9]
Other plugins seem to be installing fine.  This one is throwing an npm error.  It looks like its trying to fetch from a nonexistent source...

Any ideas how to remedy this?  Is it a problem on my end?  I have tried deleting my entire .heroku folder and reinstalling...

$ heroku plugins:install heroku-fork
Installing plugin heroku-fork...  ▸    npm ERR! fetch failed http://heroku-plugins-npm.herokuapp.com/ini/-/ini-1.3.4.tgz
 ▸    npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
 ▸    npm ERR! fetch failed http://heroku-plugins-npm.herokuapp.com/ini/-/ini-1.3.4.tgz
 ▸    npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
 ▸    npm ERR! fetch failed http://heroku-plugins-npm.herokuapp.com/ini/-/ini-1.3.4.tgz
 ▸    npm ERR! Darwin 14.1.0
 ▸    npm ERR! argv "/Users/andrewpalmer/.heroku/iojs-v2.2.1-darwin-x64/bin/iojs" "/Users/andrewpalmer/.heroku/iojs-v2.2.1-darwin-x64/lib/node_modules/npm/cli.js" "install" "heroku-fork"
 ▸    npm ERR! node v2.2.1
 ▸    npm ERR! npm  v2.11.0
 ▸  
 ▸    npm ERR! fetch failed with status code 404
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     https://github.com/npm/npm/issues
 ▸  
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /Users/andrewpalmer/.heroku/npm-debug.log

**Comment by jdx** [comment]
I put some debugging code around this. Can you update then try again with `GODE_DEBUG=1`?
